//SELECT TABLESPACE_NAME, FILE_NAME, BYTES/1024/1024 AS SIZE_MB, STATUS FROM DBA_DATA_FILES;
//SELECT PROPERTY_NAME, PROPERTY_VALUE FROM DATABASE_PROPERTIES WHERE PROPERTY_NAME = 'DEFAULT_PERMANENT_TABLESPACE';
//CREATE TABLESPACE BDDING_TBS DATAFILE 'C:\app\Djalil\oradata\BDDING\HospitalisationFile01.dbf' SIZE 50M AUTOEXTEND ON NEXT 10M MAXSIZE 100M;
//CREATE TEMPORARY TABLESPACE BDDING_TEMP_TBS TEMPFILE 'C:\app\Djalil\oradata\BDDING\TempFile01.dbf' SIZE 50M;
//CREATE USER USERBDDING IDENTIFIED BY userbdd123 DEFAULT TABLESPACE BDDING_TBS QUOTA 100M ON USERS;
//GRANT CONNECT, RESOURCE TO USERBDDING;
//GRANT ALL PRIVILEGES TO USERBDDING;
//GRANT CREATE TRIGGER TO USERBDDING;
//ALTER USER USERBDDING IDENTIFIED BY sys;